services:
    mailpit:
        image: axllent/mailpit
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATA_FILE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
    postgres:
        image: postgres
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: jobSearchHelper
            POSTGRES_USER: nirjan
            POSTGRES_PASSWORD: password
